### PR TITLE
remove unneeded cart headers

### PR DESCRIPTION
**Pull request by mchaarawi**
Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

### CODE REVIEW

**Comment by soumagne** [comment]
I assume you tested it right? I can't remember why I had left them in but I think there was a reason but it's no longer needed or it was only required by a specific DAOS version? if that's the case, we should make sure we bump the min required version.

**Comment by mchaarawi** [comment]
> I assume you tested it right? I can't remember why I had left them in but I think there was a reason but maybe it's no longer needed? or it was only required by a specific DAOS version? if that's the case, we should make sure we bump the min required version.

the cart API was needed when you were creating the cart context, and that is not required anymore. so no need to include the headers. the gurt APIs were only needed if you are using the d_* helper functions.
hmm actually thinking about this, you might need for the d_rank_list_t stuff when using DAOS 1.0.
so let me add those back actually.

**Comment by soumagne** [comment]
we don't support DAOS 1.0 anymore though? The current min version we support for DAOS is 1.1.1.

**Comment by mchaarawi** [comment]
> we don't support DAOS 1.0 anymore though? The current min version we support for DAOS is 1.1.1.

yea that still has the svcl setting required, so it might break building with that version if we remove the gurt headers.
i just wanted to remove the cart header because building the RPMs for the CI makes it that it requires boost-devel and it was not necessary.

**Review by soumagne — APPROVED** [review]

**Review by jhendersonHDF — APPROVED** [review]

**Pull request merged**
