### PR TITLE
OID generate API version check

### PR DESCRIPTION
**Pull request by mchaarawi**
add version check for oid generate API that was updated to use object
types instead of features as of 2.0 and after.

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

### CODE REVIEW

**Review by soumagne — APPROVED** [review]

**Comment by mchaarawi** [comment]
any feedback on this PR @jhendersonHDF ?

**Comment by mchaarawi** [comment]
> > any feedback on this PR @jhendersonHDF ?
> 
> Is the DKEY_HASHED object type irrelevant now? Other than that, LGTM.

well hashed type is the default if you don't specify it. so this PR doesn't change anything other than update the API usage.
one question i had is why do we use lexical akeys in this case for non groups?

**Comment by jhendersonHDF** [comment]
> well hashed type is the default if you don't specify it. so this PR doesn't change anything other than update the API usage. one question i had is why do we use lexical akeys in this case for non groups?

I believe the reason for lexical akeys on non groups is to support H5A routines that can work on attributes on objects by either creation order or name order.

**Comment by mchaarawi** [comment]
> > well hashed type is the default if you don't specify it. so this PR doesn't change anything other than update the API usage. one question i had is why do we use lexical akeys in this case for non groups?
> 
> I believe the reason for lexical akeys on non groups is to support H5A routines that can work on attributes on objects by either creation order or name order.

ah i see. thx

**Review by jhendersonHDF — APPROVED** [review]

**Pull request merged**
